language: node_js

node_js:
  - 14.16.1

before_install:
  - git config --global user.email "me@mavelar.com"
  - git config --global user.name "Manuel Avelar"
  - npm install yarn -g
  - yarn add coverage -g
  - yarn install
  - yarn build

scripts:
  - jest --ci --coverage
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  - CODECOV_TOKEN=9ebcdebc-3989-473c-9ada-3fd181965724

email:
  recipients:
    - me@mavelar.com
  on_success: change
  on_failure: always

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      name: 'Test / Coverage'
      script: yarn test:coverage

stages:
  - test