language: node_js

node_js:
  - 14.16.1

before_install:
  - git config --global user.email "me@mavelar.com"
  - git config --global user.name "Manuel Avelar"
  - npm install yarn -g
  - yarn install

email:
  recipients:
    - me@mavelar.com
  on_success: change
  on_failure: always

jobs:
  include:
    - stage: build
      name: 'Build'
      script: yarn build
    - stage: test
      name: 'Test / Coverage'
      script: yarn test:coverage
