language: node_js

node_js:
  - 14.16.1

before_install:
  - git config --global user.email "me@mavelar.com"
  - git config --global user.name "Manuel Avelar"
  - npm install yarn -g
  - yarn build

email:
  recipients:
    - me@mavelar.com
  on_success: change
  on_failure: always

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: coverage
      name: 'Coverage'
      script: yarn coverage
      
    - stage: test
      name: 'Test'
      script: yarn test
