coverage:
  status:
    project:
      default:
        target: 80%    # the required coverage value
        threshold: 0%  # the leniency in hitting the target
        base: auto
        flags: 
          - unit
        paths: 
          - "src"
        branches: 
          - main
        if_ci_failed: error
        # informational: false
        # only_pulls: false
  comment:
    layout: "reach, diff, flags, files"
