coverage:
  status:
    project:
      default:
        target: 20%    # the required coverage value
        threshold: 20%  # the leniency in hitting the target
        flags: 
          - unit
        paths: 
          - "src"
        if_ci_failed: error
        # informational: false
        # only_pulls: false
  comment:
    layout: "reach, diff, flags, files"

codecov:
  disable_default_path_fixes: false
