coverage:
  round: up
  precision: 5
  status:
    project:
      default:
        target: 90%
        threshold: 5%
      core-models:
        flags:
          - core-models
comment:
    layout: "reach, diff, flags, files"
ignore:
  - "deprecated"
