codecov:
  bot: "flipper"
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
coverage:
  status:
    project: 
      default:
        target: 90%
        threshold: 5%
        paths: 
          - "src"
        if_ci_failed: error
        # informational: true
        # only_pulls: false
  comment:
    layout: "reach, diff, flags, files"
