codecov:
  token: "9ebcdebc-3989-473c-9ada-3fd181965724"
  bot: "flipper"
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
coverage:
  status:
    patch:
      default:
        target: 10%
        threshold: 0%
        flags: 
          - unit
        paths: 
          - "src"
        if_ci_failed: error
        # informational: false
        # only_pulls: false
  comment:
    layout: "reach, diff, flags, files"
