#!/bin/sh

# Check if this is the initial commit

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	echo "pre-commit: About to create a new commit..."
	against=HEAD
else
	echo "pre-commit: About to create the first commit..."
	against=$(git hash-object -t tree /dev/null)
fi

# Use git diff-index to check for whitespace errors

echo "pre-commit: Testing for whitespace errors..."

if ! git diff-index --check --cached $against
	then echo "pre-commit: Aborting commit due to whitespace errors" exit 1
	else echo "pre-commit: No whitespace errors :)" exit 0
fi