#! /usr/bin/env node
const xml2js = require('xml2js');
const fs = require('fs');

const parser = new xml2js.Parser(/* options */);

async function readFile(filename) {
    return parser.parseStringPromise(await fs.readFileAsync(filename));
}

async function run() {
    const coverage = await readFile('../coverage/clover.xml');
    const metric = readMetric(coverage, { thresholdAlert, thresholdWarning });
}

run();