name: GitHub Actions Demo

on: [pull_request]

jobs:
  CoverageReport:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1

      - run: nvm use

      - run: yarn

      - run: yarn build

      - run: yarn test --ci --coverage --silent --watchAll=false || exit 0

      - name: Coverage Report
        uses: lessthan3/coverage-monitor-action@1.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "coverage/clover.xml"
          threshold_alert: 95
          threshold_warning: 98