name: GitHub Actions Demo

on:
  pull_request:
    branches:
      - main

jobs:
  CoverageReport:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1

      - run: yarn

      - run: yarn build

      - run: yarn test --ci --coverage --watchAll=false || exit 0

      - name: Coverage Report
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "95"
          filename: "coverage/clover.xml"
          exit: false

