name: GitHub Actions Demo

on:
  pull_request:
    branches:
      - main

jobs:
  JestCoverageReport:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1

      - run: yarn

      - run: yarn build

      - name: Coverage Report
        uses: mavelar/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 95