name: GitHub Actions Demo

on:
  pull_request:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1

      - run: nvm use

      - run: yarn

      - run: yarn build

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80
