name: GitHub Actions Demo

on:
  pull_request:
    branches:
      - main

jobs:
  JestCoverageReport:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1

      - run: yarn

      - run: yarn build

      - run: yarn test --ci --coverage

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80
  
  CodeCoverageReport:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v1

      - run: yarn

      - run: yarn build

      - run: yarn test --ci --coverage

      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.11
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

