name: GitHub Actions Demo

on:
  pull_request:
    branches:
      - main

jobs:
  CoverageReport:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1

      - run: yarn

      - run: yarn build

      - run: yarn test --ci --coverage --watchAll=false || exit 0

      - name: Coverage Report
        uses: slavcodev/coverage-monitor-action@1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "coverage/clover.xml"
          threshold_alert: 10
          threshold_warning: 60
